#!/bin/bash

#	HPC Instance Manager © 2015 Data Shades
#	Developed by shane.davis@linkdigital.com.au

#	The MIT License (MIT)

# kill-cluster: Terminates spot instances within the cluster. 


# --------------------------------------------------------------------------
# Script Defaults

launch_group=cloud-hpc
az_group=cloud-hpc

# --------------------------------------------------------------------------
# Script Functionality

# Tell the user what's going to happen
echo -e "Killing Slurm Compute Nodes\r\n"

# AWS variables for running CLI commands
placement=$(wget -q -O - http://169.254.169.254/latest/meta-data/placement/availability-zone)
region=$(echo ${placement%?})

# Get Production Node AMI - TODO: Use aws ec2 describe-tags and jq
amitags=$(ec2-describe-tags --region $region --filter "resource-type=image" --filter "value=SLURM-NODE-GM")
ami_id=$(echo "$amitags" | awk '{print $3}')

# Get the tags for this instance
myid=$(wget -q -O - http://169.254.169.254/latest/meta-data/instance-id)

# Fixed variables for AWS CLI
PATH=/sbin:/bin:/usr/sbin:/usr/bin:/opt/aws/bin
export JAVA_HOME=/usr/lib/jvm/jre
export EC2_AMITOOL_HOME=/opt/aws/amitools/ec2
export EC2_HOME=/opt/aws/apitools/ec2

# Find compute node instances and KILL them. TODO: Narrow search so only nodes in the specific cluster are terminated
instances=$(aws ec2 describe-instances --filters "Name=image-id,Values=${ami_id}" --region ${region})
instanceids=$(echo $instances | jq '.Reservations[].Instances[].InstanceId' | tr -d '"')

echo "Killing ${instanceids[@]}"
aws ec2 terminate-instances --instance-ids ${instanceids} --region ${region}

